name = "Project SPC"
author = "Thecat8413"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "184cc26741cedc0c162eebcddee7252d72fcf51550c7cb446e2bff4513b4bb1f"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
