name = "Project SPC"
author = "Thecat8413"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2159cd0e5e08b4ebba3b427a6003bf502b140a570b8c5aa8e88bb9dc57b2ccd3"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
