name = "Project SPC"
author = "Thecat8413"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcd4ae56b8f514aa8a041d30374521b161f03e0b0e77b38ae882c6e942a6fba0"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
