name = "Project SPC"
author = "Thecat8413"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29908f5b4ecfe261b9e89dc219cfab2041512c958b6927e2d913b47d8c73ee3a"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
