name = "Project SPC"
author = "Thecat8413"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07aa58783f7548ecfb30c409bf204c17640f3a6015767340de4f612a652d4cf7"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
