name = "Project SPC"
author = "Thecat8413"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50716f2d02f2c4bd2d9a91b3c6135dca17062669f7d19435f2664f7e1a0102f8"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
