name = "Project SPC"
author = "Thecat8413"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afa42817603d9c792f4335c18345fecdf6b9b0a9a08092a00fe1e2ba63df2adf"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
