name = "Project SPC"
author = "Thecat8413"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02919725c2cd28148d11c842a10bad955a5385895968ce537606ea17f55bee7e"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
