name = "Project SPC"
author = "Thecat8413"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99b9abf99b51e7f18227c126d01425fd449c2143bed379698acccfad634cbdd4"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
