name = "Project SPC"
author = "Thecat8413"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0a2831804249e9f266b64bdb5655cb36b0190f542a35059a7b3951a6ae7236b"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
